name: PythonCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter: 
    runs-on: ubuntu-latest
    
    steps:      
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: install poetry
        run: pip install poetry
      - name: install dependency
        run: make install  
      - name: lint
        run: make lint
      - name: code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: a111b80e6401182b982eeec6482d902139ffe5ee8dd38e6c2678d9f111e71b3f
        with:
          coverageCommand: make coverage
